//Client request
GET http://localhost:3000/dashboard?id=1&rol=1
content-type: application/json


//Supplier request
GET http://localhost:3000/dashboard?id=2&rol=2
content-type: application/json


//Investor request
GET http://localhost:3000/dashboard?id=3&rol=3
content-type: application/json



POST http://localhost:3000/new_invoice
Content-Type: application/json

{
"userData": {
    "id": "2",
    "rol": "2"
    },
"invoiceData": {
    "id_emission": "100019",
    "em_date": "2019-1-19",
    "exp_date": "2019-3-19",
    "amount": 200000,
    "factoring_amount": 150000,
    "min_inversion": 500,
    "roi": 1.2,
    "owner": "Proveedores de Servicios",
    "debtor": "Telefónica"
    }
}

PUT http://localhost:3000/state
Content-Type: application/json

{
"userData":{
        "id": "1",
        "rol": 1
    },
"invoiceData":{
        "id": "32",
        "state": 2
    }
}