GET http://localhost:3000/users

POST http://localhost:3000/users
content-type: application/json

{
    "rol": "3",
    "email": "i01@example.com",
    "password": "12345678",
    "tel": "231-2331",
    "company": "Smart Investors"
}


PUT http://localhost:3000/users
content-type: application/json

{
    "id": "1",
    "email":"bot0111@example.com",
    "password": "987654332"
}

DELETE http://localhost:3000/users
content-type: application/json

{
    "id": "4"
}

