-- MySQL Script generated by MySQL Workbench
-- mar 16 abr 2019 12:17:26 EST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema factoringdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema factoringdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `factoringdb` DEFAULT CHARACTER SET utf8 ;
USE `factoringdb` ;

-- -----------------------------------------------------
-- Table `factoringdb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `factoringdb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `company` VARCHAR(100) NOT NULL,
  `rol` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `factoringdb`.`invoices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `factoringdb`.`invoices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_emission` INT NOT NULL,
  `em_date` TIMESTAMP NOT NULL,
  `state` INT NOT NULL DEFAULT 1,
  `amount` DOUBLE NOT NULL,
  `factoring_amount` DOUBLE NOT NULL,
  `min_inversion` DOUBLE NOT NULL,
  `current_factoring` DOUBLE NOT NULL DEFAULT 0,
  `roi` DOUBLE NOT NULL,
  `owner` VARCHAR(100) NOT NULL,
  `emitter` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_emission_UNIQUE` (`id_emission` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `factoringdb`.`user_invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `factoringdb`.`user_invoice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `invoices_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`, `invoices_id`),
  INDEX `fk_user_invoice_users_idx` (`users_id` ASC),
  INDEX `fk_user_invoice_invoices1_idx` (`invoices_id` ASC),
  CONSTRAINT `fk_user_invoice_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `factoringdb`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_invoice_invoices1`
    FOREIGN KEY (`invoices_id`)
    REFERENCES `factoringdb`.`invoices` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `factoringdb`.`investor_invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `factoringdb`.`investor_invoice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `inversion` DOUBLE NOT NULL,
  `user_invoice_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_invoice_id`),
  INDEX `fk_investor_invoice_user_invoice1_idx` (`user_invoice_id` ASC),
  CONSTRAINT `fk_investor_invoice_user_invoice1`
    FOREIGN KEY (`user_invoice_id`)
    REFERENCES `factoringdb`.`user_invoice` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
